services:
  - type: web
    name: mdt-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true 